### ISSUE TITLE
Add cors support

### ISSUE THREAD

**Issue by zardoy** [tycrek/mulv#6]
Nice project. Would you mind adding cors support, please? To test: open `about:blank` in console type `fetch('https://mulv.tycrek.dev/api/lookup?username=dev')`

**Comment by tycrek** [comment]
Done :3 
![image](https://github.com/tycrek/mulv/assets/29926144/f9e1026d-2d8f-4a28-bd05-3a0bb046a9b6)

**Comment by tycrek** [comment]
> Also I'm just curious is it possible to pull the cape data as well?

Yes! I just pushed it in https://github.com/tycrek/mulv/commit/034427c005aa268e9fa738b7ec60ac18272d70bd. I can also try to add Optifine capes if you're interested.

![image](https://github.com/tycrek/mulv/assets/29926144/e9351826-bd42-4617-a6a0-8ffab8d2e84e)

**Comment by zardoy** [comment]
Thank you so much! We've been using it for a while it just works perfectly (including capes support). I didn't get requests to support optifine skins yet.

Also I'm just curious, do you know is it possible to build a similar project / functionality on Vercel that would receive a list of servers and output motd / status for each of them (like mcsrvstat.us does)?

**Comment by zardoy** [comment]
@tycrek hey you have a really nice project that is being used by hundreds or even thousands of players. But i wonder if it would be possible to build a similar service for getting server resource packs? Since servers owners test resource packs urls (which lead to zip files) they never add cors support which is a huge issue for a web app. And i wonder if it would be possible to build a proxy that would download resource pack and send it back to the client with cors headers?
